// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    mileageReadings,
    settings,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mileageReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'mileage_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(vehicle_id, fecha)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get marca =>
      columnsByName['marca']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get modelo =>
      columnsByName['modelo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get anio =>
      columnsByName['anio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get matricula =>
      columnsByName['matricula']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get combustible =>
      columnsByName['combustible']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fechaMatriculacion =>
      columnsByName['fecha_matriculacion']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorValor =>
      columnsByName['color_valor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fotoPath =>
      columnsByName['foto_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vin =>
      columnsByName['vin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notas =>
      columnsByName['notas']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivado =>
      columnsByName['archivado']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'marca',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'modelo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'anio',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'matricula',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'combustible',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fecha_matriculacion',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_valor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'foto_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vin',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notas',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'creado_en',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archivado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archivado IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get km =>
      columnsByName['km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get origen =>
      columnsByName['origen']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'vehicle_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES vehicles(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fecha',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'km',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origen',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoKmPorDefecto =>
      columnsByName['aviso_km_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoDiasPorDefecto =>
      columnsByName['aviso_dias_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get diasRecordatorioLectura =>
      columnsByName['dias_recordatorio_lectura']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fechaUltimaCopia =>
      columnsByName['fecha_ultima_copia']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'aviso_km_por_defecto',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1000',
      defaultValue: const i1.CustomExpression('1000'),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'aviso_dias_por_defecto',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 30',
      defaultValue: const i1.CustomExpression('30'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dias_recordatorio_lectura',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 15',
      defaultValue: const i1.CustomExpression('15'),
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tema',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'automatico\'',
      defaultValue: const i1.CustomExpression('\'automatico\''),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fecha_ultima_copia',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    mileageReadings,
    settings,
    maintenanceSchedules,
    maintenanceRecords,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mileageReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'mileage_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(vehicle_id, fecha)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 maintenanceSchedules = Shape3(
    source: i0.VersionedTable(
      entityName: 'maintenance_schedules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 maintenanceRecords = Shape4(
    source: i0.VersionedTable(
      entityName: 'maintenance_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_34,
        _column_16,
        _column_17,
        _column_35,
        _column_36,
        _column_12,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoria =>
      columnsByName['categoria']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intervalKm =>
      columnsByName['interval_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get intervalMeses =>
      columnsByName['interval_meses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoKm =>
      columnsByName['aviso_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoDias =>
      columnsByName['aviso_dias']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activo =>
      columnsByName['activo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get silenciado =>
      columnsByName['silenciado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nombre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'categoria',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_km',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_meses',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'aviso_km',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'aviso_dias',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'activo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (activo IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'silenciado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (silenciado IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'orden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scheduleId =>
      columnsByName['schedule_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get km =>
      columnsByName['km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get coste =>
      columnsByName['coste']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get taller =>
      columnsByName['taller']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notas =>
      columnsByName['notas']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get esSembrado =>
      columnsByName['es_sembrado']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schedule_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES maintenance_schedules(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<double> _column_35(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'coste',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'taller',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'es_sembrado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (es_sembrado IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    mileageReadings,
    settings,
    maintenanceSchedules,
    maintenanceRecords,
    vehicleSpecifications,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mileageReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'mileage_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(vehicle_id, fecha)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 maintenanceSchedules = Shape3(
    source: i0.VersionedTable(
      entityName: 'maintenance_schedules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 maintenanceRecords = Shape4(
    source: i0.VersionedTable(
      entityName: 'maintenance_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_34,
        _column_16,
        _column_17,
        _column_35,
        _column_36,
        _column_12,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 vehicleSpecifications = Shape5(
    source: i0.VersionedTable(
      entityName: 'vehicle_specifications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(vehicle_id)'],
      columns: [
        _column_15,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get generacion =>
      columnsByName['generacion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get motorCodigo =>
      columnsByName['motor_codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cilindradaCc =>
      columnsByName['cilindrada_cc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get potenciaKw =>
      columnsByName['potencia_kw']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tipoCaja =>
      columnsByName['tipo_caja']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get numeroMarchas =>
      columnsByName['numero_marchas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get traccion =>
      columnsByName['traccion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get codigoTecnico =>
      columnsByName['codigo_tecnico']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notasTecnicas =>
      columnsByName['notas_tecnicas']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'generacion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'motor_codigo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cilindrada_cc',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'potencia_kw',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo_caja',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'numero_marchas',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'traccion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'codigo_tecnico',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notas_tecnicas',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    mileageReadings,
    settings,
    maintenanceSchedules,
    maintenanceRecords,
    vehicleSpecifications,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mileageReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'mileage_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(vehicle_id, fecha)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 maintenanceSchedules = Shape6(
    source: i0.VersionedTable(
      entityName: 'maintenance_schedules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 maintenanceRecords = Shape4(
    source: i0.VersionedTable(
      entityName: 'maintenance_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_34,
        _column_16,
        _column_17,
        _column_35,
        _column_36,
        _column_12,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 vehicleSpecifications = Shape5(
    source: i0.VersionedTable(
      entityName: 'vehicle_specifications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(vehicle_id)'],
      columns: [
        _column_15,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoria =>
      columnsByName['categoria']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intervalKm =>
      columnsByName['interval_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get intervalMeses =>
      columnsByName['interval_meses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoKm =>
      columnsByName['aviso_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoDias =>
      columnsByName['aviso_dias']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activo =>
      columnsByName['activo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get silenciado =>
      columnsByName['silenciado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fuenteIntervalo =>
      columnsByName['fuente_intervalo']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fuente_intervalo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'orientativo\'',
      defaultValue: const i1.CustomExpression('\'orientativo\''),
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    mileageReadings,
    settings,
    maintenanceSchedules,
    maintenanceRecords,
    vehicleSpecifications,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 mileageReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'mileage_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(vehicle_id, fecha)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 maintenanceSchedules = Shape7(
    source: i0.VersionedTable(
      entityName: 'maintenance_schedules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 maintenanceRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'maintenance_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_34,
        _column_16,
        _column_17,
        _column_35,
        _column_36,
        _column_12,
        _column_37,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 vehicleSpecifications = Shape5(
    source: i0.VersionedTable(
      entityName: 'vehicle_specifications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(vehicle_id)'],
      columns: [
        _column_15,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoria =>
      columnsByName['categoria']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intervalKm =>
      columnsByName['interval_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get intervalMeses =>
      columnsByName['interval_meses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoKm =>
      columnsByName['aviso_km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoDias =>
      columnsByName['aviso_dias']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activo =>
      columnsByName['activo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get silenciado =>
      columnsByName['silenciado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fuenteIntervalo =>
      columnsByName['fuente_intervalo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get posicion =>
      columnsByName['posicion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get nombreAutogenerado =>
      columnsByName['nombre_autogenerado']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'posicion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nombre_autogenerado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (nombre_autogenerado IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scheduleId =>
      columnsByName['schedule_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get km =>
      columnsByName['km']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get coste =>
      columnsByName['coste']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get taller =>
      columnsByName['taller']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notas =>
      columnsByName['notas']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get esSembrado =>
      columnsByName['es_sembrado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
