/// Catálogo de marcas y modelos para sugerir al dar de alta un vehículo.
///
/// Cubre las marcas que se venden o se han vendido en España y sus modelos
/// más habituales. **No pretende ser exhaustivo**: faltan versiones,
/// modelos antiguos y coches de importación. Por eso los campos del
/// formulario admiten escribir un valor que no esté en la lista — la lista
/// sugiere, nunca obliga.
library;

/// Marcas ordenadas alfabéticamente, cada una con sus modelos.
const Map<String, List<String>> catalogoVehiculos = {
  'Abarth': ['500', '595', '695', '124 Spider'],
  'Alfa Romeo': [
    'Giulia',
    'Giulietta',
    'Stelvio',
    'Tonale',
    'Junior',
    'Mito',
    '147',
    '156',
    '159',
    'Brera',
  ],
  'Aston Martin': ['DB11', 'DB12', 'Vantage', 'DBX'],
  'Audi': [
    'A1',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q6 e-tron',
    'Q7',
    'Q8',
    'TT',
    'R8',
    'e-tron GT',
  ],
  'BMW': [
    'Serie 1',
    'Serie 2',
    'Serie 3',
    'Serie 4',
    'Serie 5',
    'Serie 6',
    'Serie 7',
    'Serie 8',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z4',
    'i3',
    'i4',
    'iX',
    'iX1',
    'iX3',
  ],
  'BYD': ['Atto 3', 'Dolphin', 'Seal', 'Seal U', 'Han', 'Tang'],
  'Citroën': [
    'C1',
    'C2',
    'C3',
    'C3 Aircross',
    'C4',
    'C4 Cactus',
    'C4 Picasso',
    'C4 X',
    'C5',
    'C5 Aircross',
    'C5 X',
    'C15',
    'Berlingo',
    'Jumpy',
    'Jumper',
    'Xsara',
    'Saxo',
    'ë-C3',
    'ë-C4',
    'Ami',
  ],
  'Cupra': ['Formentor', 'León', 'Ateca', 'Born', 'Terramar', 'Tavascan'],
  'Dacia': [
    'Sandero',
    'Duster',
    'Logan',
    'Jogger',
    'Spring',
    'Lodgy',
    'Dokker',
    'Bigster',
  ],
  'DS': ['DS 3', 'DS 4', 'DS 7', 'DS 9'],
  'Fiat': [
    '500',
    '500L',
    '500X',
    'Panda',
    'Punto',
    'Tipo',
    'Bravo',
    'Doblò',
    'Ducato',
    'Talento',
    '600',
  ],
  'Ford': [
    'Fiesta',
    'Focus',
    'Mondeo',
    'Kuga',
    'Puma',
    'EcoSport',
    'Explorer',
    'Mustang',
    'Mustang Mach-E',
    'C-Max',
    'S-Max',
    'Galaxy',
    'Ka',
    'Transit',
    'Tourneo',
    'Ranger',
  ],
  'Honda': ['Civic', 'Jazz', 'CR-V', 'HR-V', 'ZR-V', 'e:Ny1', 'Accord'],
  'Hyundai': [
    'i10',
    'i20',
    'i30',
    'i40',
    'Tucson',
    'Kona',
    'Bayon',
    'Santa Fe',
    'Ioniq',
    'Ioniq 5',
    'Ioniq 6',
    'Getz',
    'Accent',
  ],
  'Isuzu': ['D-Max'],
  'Jaguar': ['XE', 'XF', 'XJ', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type'],
  'Jeep': [
    'Renegade',
    'Compass',
    'Avenger',
    'Cherokee',
    'Grand Cherokee',
    'Wrangler',
  ],
  'Kia': [
    'Picanto',
    'Rio',
    'Ceed',
    'XCeed',
    'ProCeed',
    'Stonic',
    'Niro',
    'Sportage',
    'Sorento',
    'EV3',
    'EV6',
    'EV9',
    'Carens',
    'Venga',
  ],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Freelander',
  ],
  'Lexus': ['CT', 'IS', 'ES', 'LS', 'UX', 'NX', 'RX', 'RZ', 'LBX'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'MX-5', 'MX-30'],
  'Mercedes-Benz': [
    'Clase A',
    'Clase B',
    'Clase C',
    'Clase E',
    'Clase S',
    'CLA',
    'CLS',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'Clase G',
    'Clase V',
    'Vito',
    'Sprinter',
    'Citan',
    'EQA',
    'EQB',
    'EQC',
    'EQE',
    'EQS',
    'SL',
    'AMG GT',
  ],
  'MG': ['MG3', 'MG4', 'MG5', 'ZS', 'HS', 'EHS', 'Marvel R', 'Cyberster'],
  'Mini': ['Cooper', 'Clubman', 'Countryman', 'Cabrio', 'Aceman'],
  'Mitsubishi': ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander', 'Montero'],
  'Nissan': [
    'Micra',
    'Juke',
    'Qashqai',
    'X-Trail',
    'Leaf',
    'Ariya',
    'Note',
    'Pulsar',
    'Navara',
    'Primera',
    'Almera',
  ],
  'Opel': [
    'Corsa',
    'Astra',
    'Insignia',
    'Mokka',
    'Crossland',
    'Grandland',
    'Frontera',
    'Zafira',
    'Meriva',
    'Combo',
    'Vivaro',
    'Vectra',
    'Agila',
  ],
  'Peugeot': [
    '106',
    '107',
    '108',
    '205',
    '206',
    '207',
    '208',
    '306',
    '307',
    '308',
    '406',
    '407',
    '408',
    '508',
    '2008',
    '3008',
    '5008',
    'Partner',
    'Rifter',
    'Expert',
    'Boxer',
    'RCZ',
  ],
  'Polestar': ['2', '3', '4'],
  'Porsche': [
    '911',
    '718 Cayman',
    '718 Boxster',
    'Macan',
    'Cayenne',
    'Panamera',
    'Taycan',
  ],
  'Renault': [
    'Twingo',
    'Clio',
    'Captur',
    'Mégane',
    'Scénic',
    'Kadjar',
    'Arkana',
    'Austral',
    'Espace',
    'Laguna',
    'Talisman',
    'Kangoo',
    'Trafic',
    'Master',
    'Zoe',
    'Symbioz',
    'Rafale',
  ],
  'Seat': [
    'Ibiza',
    'León',
    'Arona',
    'Ateca',
    'Tarraco',
    'Alhambra',
    'Toledo',
    'Altea',
    'Exeo',
    'Mii',
    'Córdoba',
    'Marbella',
    'Ronda',
    'Málaga',
  ],
  'Škoda': [
    'Fabia',
    'Octavia',
    'Superb',
    'Scala',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Enyaq',
    'Elroq',
    'Rapid',
    'Roomster',
    'Yeti',
    'Citigo',
  ],
  'Smart': ['Fortwo', 'Forfour', '#1', '#3'],
  'SsangYong': ['Tivoli', 'Korando', 'Rexton', 'Musso'],
  'Subaru': ['Impreza', 'Forester', 'Outback', 'XV', 'Solterra'],
  'Suzuki': ['Swift', 'Ignis', 'Vitara', 'S-Cross', 'Jimny', 'Across'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
  'Toyota': [
    'Aygo',
    'Aygo X',
    'Yaris',
    'Yaris Cross',
    'Corolla',
    'C-HR',
    'RAV4',
    'Prius',
    'Auris',
    'Avensis',
    'Land Cruiser',
    'Hilux',
    'Proace',
    'bZ4X',
  ],
  'Volkswagen': [
    'up!',
    'Polo',
    'Golf',
    'Passat',
    'Arteon',
    'T-Cross',
    'T-Roc',
    'Taigo',
    'Tiguan',
    'Touran',
    'Sharan',
    'Touareg',
    'Caddy',
    'Transporter',
    'Amarok',
    'ID.3',
    'ID.4',
    'ID.5',
    'ID.7',
    'Scirocco',
    'Beetle',
    'Jetta',
  ],
  'Volvo': [
    'V40',
    'V60',
    'V90',
    'S60',
    'S90',
    'XC40',
    'XC60',
    'XC90',
    'EX30',
    'EX40',
    'EX90',
    'C40',
  ],
};

/// Marcas del catálogo, ya ordenadas.
List<String> get marcasConocidas => catalogoVehiculos.keys.toList();

/// Modelos sugeridos para una marca. Devuelve una lista vacía si la marca
/// no está en el catálogo, que es lo normal cuando se ha escrito a mano.
List<String> modelosDe(String marca) {
  final clave = catalogoVehiculos.keys.firstWhere(
    (m) => m.toLowerCase() == marca.trim().toLowerCase(),
    orElse: () => '',
  );
  return clave.isEmpty ? const [] : catalogoVehiculos[clave]!;
}
